Issue #487: Fix the uth build failure due to undefined reference to LDMigrate which occurs because CMK_LBDB_ON macro is not set.
Move the function body in DistBaseLB within the macro CMK_LBDB_ON

Change-Id: If3cc7c4f0a45e91df2eab133015b77ff61f4c7b5