AMPI: allow users to disable our renaming of exit() and atexit()
If a C++ application defines its own versions of these routines inside
a namespace and tries to call them, such as "Foo::exit(1);", AMPI's
header will still try to rename it, resulting in undefined reference to
"Foo::AMPI_Exit(1);".

This patch macro options so that users can compile their applications
with "ampicxx -DAMPI_RENAME_EXIT=0" and/or
"ampicxx -DAMPI_RENAME_ATEXIT=0" to disable this behavior.

Change-Id: Idade099d67b873fef1bd17731d235f0b92361d4b